---
- hosts: servers
  become: true
  become_user: root
  tasks:
    - name: Install APT Transport HTTPS
      apt: 
        state: present
        name: apt-transport-https
    - name: Install Docker
      apt:
        state: present
        name: docker.io
        update_cache: true
    - name: Enable docker
      service: 
        name: docker
        state: started
    - name: Add Google Cloud apt key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
    - name: Add kubernetes Source list
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: 'kubernetes'
    - name: Install and Update kubelet
      apt:
        state: present
        name: kubelet
        update_cache: true
    - name: Install and Update kubeadm   
      apt:
        state: present
        name: kubeadm
- hosts: masters
  become: true
  tasks:
    - name: Install and Update kubectl   
      apt:
        state: present
        name: kubectl
    - name: Install and Update kubernetes-cni   
      apt:
        state: present
        name: kubernetes-cni
        update_cache: yes
