---
- hosts: servers
  become: true
  become_user: root
  tasks:
    - name: Install and Update basic package for kubernetes
      action: >
        {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
      with_items:
         - apt-transport-https
         - docker.io 
